<?php
/**
 * @category    M2Commerce Enterprise
 * @package     M2Commerce_OrderComment
 * @copyright   Copyright (c) 2025 M2Commerce Enterprise
 * @author      dawoodgondaldev@gmail.com
 */

use M2Commerce\LogViewer\Block\LogFile;
use Magento\Framework\Escaper;

/**
 * @var LogFile $block
 * @var Escaper $escaper
 */
$logFile = $block->getFileName();
$displayLines = $block->getLinesToShowPerPageCount();
$logPath = BP . '/var/log/' . $logFile;
$previousLogUrl = $block->getLoadPreviousLogUrl();
?>
<div class="admin__page-section-item-content log-container">
    <button id="load-previous"
            data-file="<?= $escaper->escapeHtmlAttr($logFile) ?>"
            data-start="<?= $escaper->escapeHtmlAttr($displayLines)?>"
            data-display-lines="<?=$escaper->escapeHtmlAttr($displayLines)?>"
            class="action-primary">
        <?= $escaper->escapeHtml(__('Load Previous Logs')) ?>
    </button>
    <?php $message = __('Are you sure you want to delete %1 file content?', $logFile); ?>
    <?php if ($block->isDeleteAllowed()): ?>
        <a href="<?= $escaper->escapeHtmlAttr($block->getDeleteLogFile($logFile)) ?>" class="action-secondary delete"
           onclick="return confirm('<?= $escaper->escapeHtmlAttr($message) ?>');">
            <?= $escaper->escapeHtml(__('Delete File')) ?>
        </a>
    <?php endif; ?>
    <a href="<?= $escaper->escapeHtmlAttr($block->getUrl('logviewer/logfile/index')) ?>" class="action-secondary back">
        <?= $escaper->escapeHtml(__('Go Back')) ?>
    </a>
    <textarea id="log-output" rows="35"><?= /* @noEscape */  $block->tailFile($logPath, $displayLines) ?></textarea>
</div>
<script type="text/x-magento-init">
    {
        "#load-previous": {
            "M2Commerce_LogViewer/js/load-log": {
                "buttonId": "load-previous",
                "ajaxUrl": "<?= $escaper->escapeJs($previousLogUrl) ?>"
        }
    }
}
</script>
